<Project>

  <PropertyGroup>
    <Version>4.2.0</Version>
    <Owners>Tooark</Owners>
    <Company>Tooark</Company>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>icon.jpg</PackageIcon>
    <RepositoryBaseUrl>https://github.com/Tooark/nuget-tooark</RepositoryBaseUrl>
    <RepositoryUrl>$(RepositoryBaseUrl)</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryBaseUrl)/tree/main/$(MSBuildProjectName)</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU5104</WarningsNotAsErrors>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
    <Deterministic>false</Deterministic>
    <EnableSourceLink>false</EnableSourceLink>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <EnableSourceLink>true</EnableSourceLink>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Media\icon.jpg" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
