<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>Tooark.Notifications</PackageId>
    <Title>Tooark.Notifications</Title>
    <Authors>Paulo Sergio de Freitas Junior</Authors>
    <PackageTags>tooark, toolkit, notifications, alerts, .NET</PackageTags>
    <Summary>Management of notifications and alerts for .NET projects.</Summary>
    <PackageDescription>Package for creating and managing notifications and alerts for .NET applications.</PackageDescription>
    <Description>Library for creating and managing notifications and alerts, facilitating communication and monitoring for .NET projects.</Description>
  </PropertyGroup>

</Project>
