<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>Tooark.Mediator.Abstractions</PackageId>
    <Title>Tooark.Mediator.Abstractions</Title>
    <Authors>Paulo Sergio de Freitas Junior</Authors>
    <PackageTags>tooark, toolkit, mediator, mediatr, cqrs, cqs, command, query, notification, .NET, abstractions</PackageTags>
    <Summary>Mediator contracts for CQRS/CQS architectures in .NET.</Summary>
    <PackageDescription>Contracts library for requests, commands, queries, notifications and IMediator in .NET applications.</PackageDescription>
    <Description>Contracts library for mediator pattern supporting requests, commands, queries and notifications in .NET projects.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tooark.Exceptions\Tooark.Exceptions.csproj" />
  </ItemGroup>

</Project>
